# Generated by Django 4.1.2 on 2022-10-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('entity_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField()),
                ('user_password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
