# Generated by Django 4.1.2 on 2022-11-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('empname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('e_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile', models.BigIntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('entity_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField()),
                ('user_password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
