# Generated by Django 4.1.2 on 2022-12-08 14:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistModel',
            fields=[
                ('dist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dist_name', models.CharField(max_length=100)),
                ('d_email', models.EmailField(max_length=254)),
                ('d_pno', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Distributor',
            },
        ),
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('empname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('e_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile', models.BigIntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.empmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='DrgModel',
            fields=[
                ('dg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dgname', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('dist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.distmodel')),
            ],
            options={
                'db_table': 'Drugs',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('sale_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField()),
                ('stock', models.IntegerField()),
                ('age', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('amt', models.BigIntegerField(null=True)),
                ('emp_name', models.CharField(max_length=100, null=True)),
                ('drg_id', models.ManyToManyField(to='members.drgmodel')),
            ],
            options={
                'db_table': 'Bill',
            },
        ),
    ]
