# Generated by Django 4.1.2 on 2022-11-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistModel',
            fields=[
                ('dist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dist_name', models.CharField(max_length=100)),
                ('d_email', models.EmailField(max_length=254)),
                ('d_pno', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DrgModel',
            fields=[
                ('dg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dgname', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('cprice', models.IntegerField()),
                ('sprice', models.IntegerField()),
                ('dist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.distmodel')),
            ],
        ),
    ]
