# Generated by Django 4.1.2 on 2022-12-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='emp_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.empmodel'),
        ),
    ]
