# Generated by Django 4.1.2 on 2022-12-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_bill_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='emp_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
