# Generated by Django 4.1.2 on 2022-11-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_distmodel_drgmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='distmodel',
            table='Distributor',
        ),
        migrations.AlterModelTable(
            name='drgmodel',
            table='Drugs',
        ),
    ]
