# Generated by Django 4.1.2 on 2022-12-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_bill_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amt',
            field=models.IntegerField(null=True),
        ),
    ]
